name: Veenyl nightly build

on: push

jobs:
  build:
    name: Build and upload nightly build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential git meson m4 texinfo python3 python3-pip util-linux wget mtools zip && sudo pip3 install xbstrap

      - name: Build distro
        run: make distro

      - name: Build Veenyl
        run: make

      - name: Untag last nightly release
        run: ( git push --delete origin nightly || true ) && ( git tag --delete nightly || true )

      - name: Tag new nightly release
        run: git tag nightly && git push --tags

      - name: Rename veenyl.hdd
        run: mv veenyl.hdd veenyl-nightly.hdd

      - name: Zip up
        run: zip veenyl-nightly veenyl-nightly.hdd

      - name: Create nightly release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly build
          tag_name: nightly
          body: Image of an up to date veenyl nightly build.
          files: |
            veenyl-nightly.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
